apiVersion: v1
kind: Service
metadata:
    name: "k8cluster-3f5f"
    labels:
        app: "k8cluster-3f5f"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k8cluster-3f5f"